name: Auto Scrape & Upload

on:
  schedule:
    - cron: '0 4 1 1 *'  # Jährlich am 1. Januar um 4:00 Uhr UTC
  workflow_dispatch:  # Optional: Manuelles Auslösen

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install scrapy pandas pymongo

      - name: Run Scrapy Spider
        run: |
          scrapy runspider scraper/open_data_spider.py
