name: ModelOps (Update Model)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-model:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Projekt herunterladen (Checkout)
        uses: actions/checkout@v3

      - name: 🐍 Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 📦 Abhängigkeiten installieren
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📥 CSV laden & in MongoDB speichern
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          if [ -f "scraper/open_data_scraper.py" ]; then
            python scraper/open_data_scraper.py
          else
            echo "❌ Datei scraper/open_data_scraper.py nicht gefunden!"
            exit 1
          fi

      - name: 🧠 Modell trainieren
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          set -e
          if [ -f "backend/model.py" ]; then
            cd backend
            python model.py
            cd ..
          else
            echo "❌ Datei backend/model.py nicht gefunden!"
            exit 1
          fi

      - name: ☁️ Modell nach Azure Blob hochladen
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          set -e
          if [ -f "model/save.py" ]; then
            cd model
            python save.py -c "${AZURE_STORAGE_CONNECTION_STRING}"
            cd ..
          else
            echo "❌ Datei model/save.py nicht gefunden!"
            exit 1
          