name: ModelOps (Update Model)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-model:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Projekt herunterladen (Checkout)
        uses: actions/checkout@v3

      - name: 🐍 Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 📦 Abhängigkeiten installieren
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📥 CSV laden & in MongoDB speichern
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python scraper/open_data_scraper.py


      - name: 🧠 Modell trainieren
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          cd model
          python model.py
          cd ..

      - name: ☁️ Modell nach Azure Blob hochladen
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          cd model
          python save.py -c "${AZURE_STORAGE_CONNECTION_STRING}"
